### ISSUE TITLE
Find & Update ValidationError

### ISSUE THREAD

**Issue by timdavish** [blakehaswell/mongoose-unique-validator#100]
I have the following schema:
```
const UserSchema = new mongoose.Schema(
    discordId: {
      type: String,
      required: false,
      unique: true,
      sparse: true,
      trim: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
      uniqueCaseInsensitive: true,
      sparse: true,
      trim: true,
      lowercase: true,
    },
)

UserSchema.plugin(mongooseUniqueValidator, {message: '{PATH} already taken'})
```

and I'm running a `findOneAndUpdate` like so:
```
const user = await User.findOneAndUpdate(
  {
    $or: [{discordId}, {email: {$regex: `^${email}$`, $options: 'i'}}],
  },
  {
    discordId: 12345678,
    email: 'email@gmail.com',
  },
  {
    runValidators: true,
    context: 'query',
  }
)
```

Prior to running this, the user with this discordId & email can either exist or not, and either way I'm ending up with the following error:
```
{ ValidationError: Validation failed: email: email already taken, discordId: discordId already taken

{ email already taken
          at ...
        message: 'email already taken',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'unique',
        path: 'email',
        value: 'email@gmail.com',
        reason: undefined,
        '$isValidatorError': true }

{ discordId already taken
          at ...
        message: 'discordId already taken',
        name: 'ValidatorError',
        properties: [Object],
        kind: 'unique',
        path: 'discordId',
        value: '12345678',
        reason: undefined,
        '$isValidatorError': true }
```

Any thoughts? For now my workaround is to just remove `runValidators`, but this is not a permanent solution.

Using the latest version of `mongoose-unique-validator` (2.0.3)

**Comment by viveleroi** [comment]
Can you try this with v2.0.1? I wonder if it's related.

**Comment by viveleroi** [comment]
Also, can you provide more code or details on how this happens? I can't reproduce it. This issue seems very similar to issues others have and I can't reproduce any of them yet.

**Comment by timdavish** [comment]
Apologies for the late response.

A while ago I remember I quickly tried to repro this and was unable to. I'm not sure if perhaps I had a specific version that caused this, but my understanding was that the entire time we were on 2.0.3 (even when I was later unable to repro again)

We're no longer using a find & update here so this has become a non-issue.

Sorry I wasn't more help with pinpointing the cause. We can close this issue and I'll be happy to open another one if we happen to run into this again

**Comment by timdavish** [comment]
Related: #99
