### ISSUE TITLE
Custom default error message

### ISSUE THREAD

**Issue by m-weeks** [blakehaswell/mongoose-unique-validator#102]
It would be great if you could specify a default error message for all instances of the plugin, rather than having to specify it for each schema.

In mongoose, you can easily override the default errors like the following:

`mongoose.Error.messages.general.required = '{PATH} is required';`

It would be great if something similar was possible.

Something like the following:

`const message = options.message || <override message variable> || 'Error, expected `{PATH}` to be unique. Value: `{VALUE}`';`

**Comment by m-weeks** [comment]
Completed in PR #103

**Comment by viveleroi** [comment]
Please don't close issues until PRs have been reviewed and merged.
