### ISSUE TITLE
custom error messages is not explained well need help

### ISSUE THREAD

**Issue by heshamelmasry77** [blakehaswell/mongoose-unique-validator#105]
now i have my email is a unique in my schema.

```
email: {
    type: String,
    required: true,
    unique: true
  },
```

I need to put a custom message so what i did is that :

```
const User = mongoose.model('User', userSchema.plugin(uniqueValidator,{ message: 'Error, expected {PATH} to be unique.' }));

module.exports = User;

```

what is the path to be unique can't understand !!

**Comment by viveleroi** [comment]
I don't understand your question. That's how you create a custom error message, as described here https://github.com/blakehaswell/mongoose-unique-validator#custom-error-messages
