### ISSUE TITLE
Validation will always fail on updates for `_id`

### ISSUE THREAD

**Issue by m-weeks** [blakehaswell/mongoose-unique-validator#108]
I know this isn't released yet, but I see this issue on the current version introduced by b8f3e0f

The problem is that this section:
```
if (isQuery) {
    each(this._conditions, (value, key) => {
        conditions[key] = { $ne: value };
    });
} else if (this._id) {
    conditions._id = { $ne: this._id };
}
```

the `_id` condition is being overriden, where previously it was `_id: <currentId>`, it gets overridden to be `_id: { $ne : <currentId> }`. Previously both these conditions were part of the query, but now it is just one.

Now the simplest solution would be to add both conditions, but perhaps this needs some more thought

I don't think this is related to #88 as this was a recent change

**Comment by viveleroi** [comment]
Ok, how about I check for `_id`, and if it's false I can add the "overwrite" check:

```
if (isQuery) {
    each(this._conditions, (value, key) => {
        conditions[key] = { $ne: value };
    });
} else if (this._id && !conditions._id) {
    conditions._id = { $ne: this._id };
}
```

That way any changes to `_id` as a path aren't replaced by `{ $ne: this._id }`?

**Comment by brandiqa** [comment]
Has this been fixed? Just realized that when I try to update an existing record, the validation fails on a field I've set as unique.

**Comment by m-weeks** [comment]
@brandiqa This issue was introduced by some code that hasn't been released yet. Is it possible you are getting validation failures for another reason?

**Comment by brandiqa** [comment]
When I disable the plugin code, the update successful works as expected.

**Comment by mbagiella** [comment]
I have the same issue, UniqueValidator prevent my code to use findOne and save, mongoose try to create a new object instead of update the current one.

**Comment by ArnieGA** [comment]
Any updates to this?

**Comment by m-weeks** [comment]
> Any updates to this?

I opened a pull request for this about 2 1/2 years ago and it looks like 2 other people have also made their own fixes since 

#109 
#132 
#135 

I'd guess your best bet is to fork the repository and merge in one of these pull requests and maintain your own local copy
