### ISSUE TITLE
Feature request: unique model by many fields

### ISSUE THREAD

**Issue by Tolsi** [blakehaswell/mongoose-unique-validator#11]
This can be useful when creating a model where multiple fields must be unique at the same time.

**Comment by monsieurBelbo** [comment]
:+1:

**Comment by j-mcnally** [comment]
any progress on this, id like to only enforce a validation if a record isn't soft deleted.

Basically unique where archived is false.

**Comment by phillyqueso** [comment]
:+1:

**Comment by matiux** [comment]
+

**Comment by gdl276s** [comment]
+1

**Comment by gdl276s** [comment]
This article may also support this feature ...

http://stackoverflow.com/questions/14283503/unique-documents-using-multiple-values-in-mongoose-schema

**Comment by viveleroi** [comment]
The ideas in this issue have sort of diverged.

I've added proper handling of unique compound indices as described in #28. For those wanting to validate a group of fields together, that should provide what you need.

@j-mcnally suggested a way to further limit the query which does sound like a valid use-case that may not be appropriate for a compound index. So I've opened it in #30.
