### ISSUE TITLE
Allowing Duplicates 

### ISSUE THREAD

**Issue by zulqarnain26** [blakehaswell/mongoose-unique-validator#113]
I've followed the mentioned steps but still duplicates are being allowed in db.

var uniqueValidator = require('mongoose-unique-validator');
var Users = new Schema();
Users.plugin(uniqueValidator);

newUser.save(function(err1) {
            if (err1) return handleError(err1);
});

**Comment by viveleroi** [comment]
Your schema has no unique indexes.

**Comment by zulqarnain26** [comment]
my schema has unique indexes i have not written for the sake of simplicity.

var Users = new Schema(
  {
    email: {
      type: String,
      required: true,
      allowNull: false,
      isUnique: true,
    },
    password: {
      type: String,
      required: true,
      allowNull: false,
    },
    userchars: [{ type: Schema.Types.ObjectId, ref: 'UserChars' }],
    parentdata: [{ type: Schema.Types.ObjectId, ref: 'ParentData' }],
  },
  {
    collection: 'Users',
  }
);var Users = new Schema(
  {
    email: {
      type: String,
      required: true,
      allowNull: false,
      isUnique: true,
    },
    password: {
      type: String,
      required: true,
      allowNull: false,
    },
  },
  {
    collection: 'Users',
  }
);

**Comment by viveleroi** [comment]
Please refer to the documentation or run the test suite yourself for examples.

Your schema is missing `unique`. Don't leave out stuff for "simplicity", you're misleading people.
