### ISSUE TITLE
Mongoose Multiple Field (Compound) Unique Indexes 

### ISSUE THREAD

**Issue by satya-vinay** [blakehaswell/mongoose-unique-validator#114]
Can we use this package for **Mongoose Multiple Field (Compound) Unique Indexes**, if yes please give  me an example?

**Comment by m-weeks** [comment]
It should work for compound indexes as long as you specify it as a unique index like so:

```
var schema = new mongoose.Schema({
    username: {
        type: String
    },
    email: {
        type: String,
        index: true
    },
    password: {
        type: String
    }
});

schema.index({ username: 1, email: 1 }, { unique: true });

return schema;
```

**Comment by theolevisage** [comment]
But this returns a Mongo error, right ? What if we want to go through unique-validator to enjoy the error customization ? 
Do we have to make it like @m-weeks  showed and then plugin ? Like so : 
`var schema = new mongoose.Schema({
    username: {
        type: String
    },
    email: {
        type: String,
        index: true
    },
    password: {
        type: String
    }
});

schema.index({ username: 1, email: 1 }, { unique: true });

schema.plugin(uniqueValidator, {type : 'unique-error-of-some-sort'});

return schema;`
