### ISSUE TITLE
mongoose-unique-validator is not working when update by using findByIdAndUpdate

### ISSUE THREAD

**Issue by BlueDragon1105** [blakehaswell/mongoose-unique-validator#115]
When create new document, this unique validation is working well.
But when update existing one, this validation is not working at all.
I tried to set runValidators to be true but problem is still remaining.
Hope your kind help.
Thanks.

**Comment by viveleroi** [comment]
Works fine in the test suite. Can't help further.

**Comment by itsrachelfish** [comment]
@viveleroi I'm getting this same issue. Is there any information that would be useful to you?

**Comment by itsrachelfish** [comment]
@BlueDragon1105 @viveleroi Managed to figure it out!

Just needed to use the `runValidators` option. https://mongoosejs.com/docs/validation.html#update-validators

Which of course is already mentioned in the docs :)

https://github.com/blakehaswell/mongoose-unique-validator#find--updates
