### ISSUE TITLE
Please deprecate this package altogether!

### ISSUE THREAD

**Issue by unicornist** [blakehaswell/mongoose-unique-validator#116]
I really appreciate all the effort taken for this package, but this is definitely an outdated solution after mongoose [4.5 / May 2016](https://github.com/Automattic/mongoose/issues/2284#ref-commit-6e66276).
Also at the end of the document it states an important issue (that was described [here](https://github.com/Automattic/mongoose/issues/2284#issuecomment-93393304) just after this solution was born) with this package saying there is no current work around and not a big problem for many users!
So my suggestion is to deprecate this package from npm inf favor of [mongoose-beautiful-unique-validation](https://github.com/matteodelabre/mongoose-beautiful-unique-validation) which does the job properly using the mongoose update after this package.

All the history of this requirement and solutions could be tracked at one of mongoose issues: https://github.com/Automattic/mongoose/issues/2284

Cheers!

**Comment by unicornist** [comment]
The mongoose-native solution without a plugin:
http://thecodebarbarian.com/mongoose-error-handling.html

A plugin that just does the above: https://github.com/jhenriquez/mongoose-mongodb-errors

**Comment by viveleroi** [comment]
Who the hell goes around telling people to deprecate their work. Jesus Christ.
