### ISSUE TITLE
Do not fail validation if sparse option is true and value is empty.

### ISSUE THREAD

**Issue by shakiba** [blakehaswell/mongoose-unique-validator#12]
When sparse option is set to true and value is empty, validation should be passed.  For example: 
```js
new Schema({
  email : {
    type : String,
    unique : true,
    sparse : true
  }
});
```

**Comment by viveleroi** [comment]
The recent rewrite seems to have fixed this issue as well. I have added two unit tests to ensure it works as expected, so please let us know how the next release works for you.
