### ISSUE TITLE
Following docs, still getting standard error message instead of custom error

### ISSUE THREAD

**Issue by jacobedawson** [blakehaswell/mongoose-unique-validator#121]
Hi, 

I am following the docs in order to prevent duplicate names in a user collection. I have followed the docs since I'm using findOneAndUpdate, yet I'm still getting the standard MongoDB "DuplicateKey" error instead of the expected 'pretty' error from mongoose-unique-validator. 

My setup is as follows:

```
// user.js User Model
import mongoose, { Schema } from "mongoose";
import uniqueValidator from "mongoose-unique-validator";

const userSchema = new Schema(
  {
    name: {
      type: String,
      required: true,
      unique: true,
    },
    // ...etc
});

userSchema.plugin(uniqueValidator);
const User = mongoose.model("User", userSchema);
export default User;
```

In a user signin function I am using findOneAndUpdate:

```
export async function signin(user) {
  try {
    let dbUser = await User.findOneAndUpdate(
      {
        email: user.email
      },
      {
        $setOnInsert: {
          ...user
        }
      },
      defaultOptions
    ).exec();
    // ...other code
    return dbUser;
} catch (error) {
  throw new Error(error);
}
```

The user data I am passing into this function (while testing) is like so:

```
// first time, user is created as expected with email & name
{
  email: "a",
  name: "x"
}

// second time, new email duplicate name to throw error
{
  email: "b",
  name: "x"
}
```
As per the mongoose-unique-validator documents, I am setting 'runValidators' and 'context' on my defaultOptions:
```
// defaultOptions.js
export default {
  new: true,
  upsert: true,
  setDefaultsOnInsert: true,
  setOnInsert: true,
  useFindAndModify: false,
  runValidators: true,
  context: "query"
};
```

I've spent 2 hours trying to debug this and I can't work out what is missing. According to the docs this configuration should make mongoose-unique-validator return a custom error (e.g. not the default MongoDB E11000 error). 

Is there something I'm missing?

UPDATE:

Looks like this is caused by a years old inability of mongoose to to run validators when using $setOnInsert (as opposed to $set).
- https://github.com/Automattic/mongoose/issues/3124
- https://stackoverflow.com/questions/31101984/mongoose-findoneandupdate-and-runvalidators-not-working

When using $set it works :/

**Comment by Freivincampbell** [comment]
I was getting the same error, what I did was, delete my documents and restart my terminal, and it started working. 


Have you try that?

**Comment by viveleroi** [comment]
Apologies in the delay to reply. While reading your issue I instantly felt it might be because you had `$setOnInsert`. Because this seems like it's due to how mongoose works internally, I'll close this.
