### ISSUE TITLE
Custom Error Messages : Cannot set property 'message' of undefined

### ISSUE THREAD

**Issue by ImNeos** [blakehaswell/mongoose-unique-validator#126]
Hello, 
I am trying to use custom error messages. here is my schema : 

const mongoose = require ('mongoose'); 
var uniqueValidator = require('mongoose-unique-validator');

const userSchema = mongoose.Schema({
    email : {type : String, required : true, unique : true},
    password: {type : String, required : true},
    pseudo : {type : String, required : true, unique : true}
})
uniqueValidator.defaults.message = 'Error, expected {PATH} to be unique.'
userSchema.plugin(uniqueValidator);

module.exports = mongoose.model('User', userSchema); 

I get this error : TypeError: Cannot set property 'message' of undefined 

Could you help me? 
Thank you

**Comment by viveleroi** [comment]
Assigning a property to `userSchema.default` may not be right depending on your build environment, that is an outdated example meant for older build outputs.

I would suggest following the first example in https://github.com/blakehaswell/mongoose-unique-validator#custom-error-messages or even setting the message directly in your schema.
