### ISSUE TITLE
More descriptive "type" property of ValidationError (instead of just "user defined")

### ISSUE THREAD

**Issue by idolize** [blakehaswell/mongoose-unique-validator#17]
Currently the **"type"** property for all errors that come from the plugin are set to the string **"user defined"**.

This makes it very difficult to determine which validation has actually failed in the error handling code. The only way I am aware of to accomplish this currently is to use the custom messages functionality and check the result.

For example:

```javascript
var userSchema = mongoose.Schema({
    username: { type: String, required: true, unique: true },
});
userSchema.plugin(uniqueValidator, { message: 'Not Unique' });
// ...

var user = new User({ username: 'JohnSmith'});
user.save(function (err) {
    if (err) {
      if (err.errors.username) {
        if (err.errors.username.message === 'Not Unique') { // should be checking "type" here
          req.flash('errors', { msg: 'Account with that username already exists.' });
          return res.redirect('/signup');
        } else {
          // some other validation error we may want to handle differently (!)
        }
      }
      else return next(err);
    }
    req.logIn(user, function(err) {
      if (err) return next(err);
      res.redirect('/');
    });
});
```

It would be great if the "type" argument was more useful/deterministic, so we could actually use the message field as it was intended: a human-readable message.

**Comment by anthonator** [comment]
The example above gives me a 404. Could we get an updated link?

**Comment by anthonator** [comment]
`user defined` looks hard coded now?

**Comment by nathanhornby** [comment]
I'm looking for the same information as @anthonator - how do I set the `kind` for custom validation? (Also, while I'm here, the docs still refer to it as `type` in the guide section, which had me confused for a while: http://mongoosejs.com/docs/api.html#schematype_SchemaType-validate).

**Comment by blakehaswell** [comment]
`type` looks to be harded-coded in Mongoose source, so we probably can’t fix this issue.
