### ISSUE TITLE
Does not work with mongoose-auto-increment plugin

### ISSUE THREAD

**Issue by MangeshPimpalkar** [blakehaswell/mongoose-unique-validator#21]
I have schema
I applied 2 plugins 

var  autoIncrement = require('mongoose-auto-increment');
var uniqueValidator = require('mongoose-unique-validator');

ProgramSchema.plugin(autoIncrement.plugin, 'Program');
ProgramSchema.plugin(uniqueValidator,{message:'Duplicate'});
mongoose.model('Program', ProgramSchema);

I get the MongoError on adding duplicate record but If I do no use autoIncrementPlugin it throws proper custom error.

Can you please check.

**Comment by MangeshMp** [comment]
I think it was a mistake on my end.

**Comment by jillmolloy** [comment]
@MangeshPimpalkar I'm having trouble getting these two plugins to work together also – what was the issue you were having?
