### ISSUE TITLE
Error when using findByIdAndUpdate with option runValidators set to true.

### ISSUE THREAD

**Issue by killfish** [blakehaswell/mongoose-unique-validator#24]
I get the following error when updating my document. 
```
Wed, 13 May 2015 17:27:55 GMT uncaughtException undefined is not a function
TypeError: undefined is not a function
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose-unique-validator/index.js:25:26
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/lib/schematype.js:674:19
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/lib/schematype.js:653:19)
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/lib/services/updateValidators.js:94:35
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/node_modules/async/lib/async.js:570:21
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/node_modules/async/lib/async.js:249:17
    at /Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Volumes/Data/WebstormProjects/projectdemo/node_modules/mongoose/node_modules/async/lib/async.js:46:24)
```
The validator works fine when saving a document but breaks when using update. Here is how I'm updating my model: 

`User.findByIdAndUpdate(req.params.id, userObj, {runValidators: true}, function (err, user) {});`

**Comment by sklyukin** [comment]
I have same issues with update.

**Comment by Splact** [comment]
Same issue here.

**Comment by viveleroi** [comment]
Running into this as well, seems like there are issues/PRs sitting untouched for all of 2015...

**Comment by viveleroi** [comment]
Looking into it, it seems that `this` is no longer what the plugin expects when run this way. It seems to me like `this` ends up being a reference to node, not mongoose or the validator.

    function (value, respond) {
        var model = this.model(this.constructor.modelName);
        // other code, but "this" isn't always the same
    }

 That may mean mongoose is invoking this function differently but I'd have to scan their code.

Problem is, I see no safe/alternative way to reference to the current model dynamically. Am looking further into it...

**Comment by viveleroi** [comment]
Ok, narrowed it down to a difference with how mongoose calls the validation logic internally. I've filed an issue here: https://github.com/Automattic/mongoose/issues/3430

I see no solution to this other than them making one of two changes.

A temporary work around is to query for the document, modify the fields, and then call `save`. That will avoid the `update

**Comment by blakehaswell** [comment]
Thanks @viveleroi.

And apologies about the issues/PRs being untouched this year; I’ve been travelling for most of the year. I’m looking for a collaborator to help maintain this project going forward. See issue #29.
