### ISSUE TITLE
Error with property "model" as name

### ISSUE THREAD

**Issue by leandono** [blakehaswell/mongoose-unique-validator#26]
Hi, having this schema:

```js
var carSchema = new mongoose.Schema({
	brand: {
		type: String,
		required: true
	},
	model: {
		type: String,
		required: true,
		unique: true
	},
	name: {
		type: String,
		required: true
	}
});
```

The plugin fails with this error:

```js
/node_modules/mongoose-unique-validator/index.js:25
        var model = this.model(this.constructor.modelName);
                         ^
TypeError: Property 'model' of object { brand: 'Renault',
  model: 'Duster',
  name: 'Expression 1.6 16v 2015/2016',
  _id: 5564c8fd125d165c085de430 } is not a function
```

Cheers

**Comment by sklyukin** [comment]
I think it is related not to "model" name but to "unique issue". Same as here - https://github.com/blakehaswell/mongoose-unique-validator/issues/24

**Comment by viveleroi** [comment]
Confirming as a duplicate. When we have a solution from the mongoose folks for #24, it should hopefully avoid this issue too. The root cause of both is that we have to use the validators `this.model` property to get a reference, so if you have a field actually named "model" it breaks.
