### ISSUE TITLE
Looking for a collaborator to help maintain this project

### ISSUE THREAD

**Issue by blakehaswell** [blakehaswell/mongoose-unique-validator#29]
I’ve been away for most of this year and I haven’t really had time to look after this project. I’m really glad to see the interest people have and I’m super excited that people have found it useful.

That said, I’m not currently using Mongoose and I haven’t followed its development over the past year, so I’m not the best person to decide what is best for this plugin going forward.

So I’m looking for expressions of interest from people who would like to be added as a collaborator to help keep this plugin up-to-date and useful for the Mongoose community. If you’re interested, please respond to this issue or send me an email: haswell00@gmail.com

**Comment by viveleroi** [comment]
Count me in.

I'm actively using mongoose for a number of projects, one of which is a major rewrite of a long-time commercial project I own so I don't foresee losing such investment anytime soon. As you've noticed, I'm a user of this plugin and am also invested in its continued existence.

I try to limit myself from volunteering for everything I'd wish to but this seems like a manageable choice.

**Comment by blakehaswell** [comment]
:+1:

**Comment by timbru31** [comment]
Thanks for keeping it alive @viveleroi :)
