### ISSUE TITLE
Support unique checks on nested objects?

### ISSUE THREAD

**Issue by srt32** [blakehaswell/mongoose-unique-validator#32]
We recently upgraded from `0.4.1` to `0.6.0` because we were interested in the compound unique index checks (ref: https://github.com/blakehaswell/mongoose-unique-validator/issues/28 and this feature is great!) but we're now noticing that nested fields marked as unique are no longer being validated where they used to be (it seems something changed between the versions I mentioned above).

I have a failing test on a branch (https://github.com/blakehaswell/mongoose-unique-validator/compare/master...srt32:st-nested-unique-fields) and I'm curious if this change of behavior is understood or if I'm doing something incorrectly.

Here's what it looks like. With a schema like:

```
 createNestedUserSchema: function() {
        return new mongoose.Schema({
            username: {
                type: String,
                unique: true
            },
            contact: {
              email: {
                  type: String,
                  index: true,
                  unique: true // field of interest
              }
            },
            password: {
                type: String
            }
        });
    },
```

note how `contact.email` has `unique: true`. Previously if there was a record saved with a duplicate `contact.email` a validation error would be thrown. Now, no error is thrown.

Here's a failing test showing the use case:

```
        it('throws error for single nested index violation', function(done) {
            var User = mongoose.model('User', helpers.createNestedUserSchema().plugin(uniqueValidator));

            var nestedUser = {
              username: 'JohnSmith',
              contact: { email: 'john.smith@gmail.com' },
              password: 'j0hnNYb0i'
            }
            var otherNestedUser = {
              username: 'BobSmith',
              contact: { email: 'john.smith@gmail.com' },
              password: 'j0hnNYb0i'
            }
            // Save the first user
            var promise = new User(nestedUser).save();
            promise.then(function() {
                // Try saving a duplicate
                new User(otherNestedUser).save().catch(function(err) {
                   // err.errors is undefined here.
                    expect(err.errors.contact.email.message).to.equal('Error, expected `contact.email` to be unique. Value: `john.smith@gmail.com`');
                    done();
                });
            });
            promise.catch(done);
        });
```

Should this test be passing?

Happy to explain more if I could clarify our intent.

**Comment by viveleroi** [comment]
I can't say for sure why it would have worked for you previously - issue #13 was filed before I took over and these appear to be the same problem. These won't be impossible to fix, just needs some effort to make it build the correct query.

I'll close the other issue because this one is more recent and you've provided a failing test which is excellent. I'll see if I can get this fixed sometime this week.

**Comment by srt32** [comment]
Thanks for the quick response, @viveleroi! If it helps at all, the dependency on `mongoose` also changed in the more recent version bumps so there may be some interaction going on there.

**Comment by viveleroi** [comment]
I've bumped the version to `0.6.1`, give that a try and let me know how it goes. I've used your test case (with one tweak for how mongoose sets keys in the `err.errors` object.

**Comment by srt32** [comment]
Amazing turnaround time. We'll test. Thanks!
