### ISSUE TITLE
Support unique checks on embedded schema

### ISSUE THREAD

**Issue by rusty1s** [blakehaswell/mongoose-unique-validator#33]
Coming from https://github.com/blakehaswell/mongoose-unique-validator/issues/32. This works just fine, but when I try to replace the nested object with an embedded schema, mongoose-unique-validator complains with an error message like:
```
/.../node_modules/mongoose-unique-validator/index.js:50
                            model = doc.model(doc.constructor.modelName);
                                        ^

TypeError: doc.model is not a function
```

Here's a simplified version of my code I'm using:
```
var nameSchema = new mongoose.Schema({
    de: {
        type: String,
        unique: true
    },
    en: {
        type: String,
        unique: true
    }
});

var schema = new mongoose.Schema({
    name: nameSchema
});
```
Any fix or help is very much appreciated. Thanks in advance :)

**Comment by viveleroi** [comment]
What version of mongoose are you using?

**Comment by rusty1s** [comment]
Im using version 0.6.0

**Comment by viveleroi** [comment]
I mean mongoose, not this plugin.

**Comment by rusty1s** [comment]
Ah sorry, version 4.2.6

**Comment by viveleroi** [comment]
I tested a nested schema following your example with mongoose 4.2.6, and while the validator isn't being called on the nested schema, I'm not seeing this error.

Does this error only show when you use the nested schema? In my tests, mongoose doesn't call validators on nested schemas, so before I pursue a solution I need to figure out why it's calling the validator for you but not for me.

**Comment by rusty1s** [comment]
Ok, so try this:

```
en: {
		type: String,
		unique: true,
		uniqueCaseInsensitive: true,
		required: true
	},

	de: {
		type: String,
		unique: true,
		uniqueCaseInsensitive: true,
		required: true
	}
```
in your nested schema. Seems like the required property is needed for this error.

**Comment by viveleroi** [comment]
So I'll probably have to write some custom logic to handle nested schemas differently than we handle nested objects because of differences in how mongoose calls the validators.

I've filed an issue for mongoose to see if there's anything they can do:
https://github.com/Automattic/mongoose/issues/3589

(They've fixed something like this before for us).

Once I hear back from them I can decide how to move forward.

**Comment by rusty1s** [comment]
Thank you very much, looking forward :)

**Comment by viveleroi** [comment]
Mongoose has landed a fix that will make this possible for us. I'll wait until they have a tagged release with this fix and then we'll update.

https://github.com/Automattic/mongoose/commit/df7a5dc5a230075021bbf2b91efe7bf8adb30962

**Comment by bmrinal** [comment]
Great! Really looking forward to it.
