### ISSUE TITLE
validateSync not using mongoose-unique-validator

### ISSUE THREAD

**Issue by vonquilon** [blakehaswell/mongoose-unique-validator#34]
When my program uses validateSync, I still get the E11000 duplicate key error. The err object is seen below:
{ [MongoError: E11000 duplicate key error index: advice.users.$email_1 dup key:
{ : "user4@example.com" }]
  name: 'MongoError',
  message: 'E11000 duplicate key error index: advice.users.$email_1 dup key: { :
 "user4@example.com" }',
  driver: true,
  index: 0,
  code: 11000,
  errmsg: 'E11000 duplicate key error index: advice.users.$email_1 dup key: { :
"user4@example.com" }' }

**Comment by viveleroi** [comment]
I'll need to do some research but you might be out of luck. `validateSync` only calls synchronous validators - but our queries for duplicate values are async by nature so we can't `return` anything.

**Comment by vonquilon** [comment]
ok, thanks. I'll do some workaround for now.

**Comment by viveleroi** [comment]
Closing, we have no way to validate anything synchronously.
