### ISSUE TITLE
Regression in v5.0.0+?

### ISSUE THREAD

**Issue by freezy** [blakehaswell/mongoose-unique-validator#38]
Bumping this plugin from v0.4.1 broke my tests. Basically I'm updating an existing entity with a new unique value that exists in the database. This used to fail but doesn't anymore with v5.0.0+. 

Something like:

```javascript
User.findOne({ id: req.params.id }, function(err, user) {
    user.email = 'existing email of another user';
    user.validate(function(err) {
        // everything dandy in here, but shouldn't!
    });
});
```

Since there is no changelog and not much documentation (neither tests) about updating existing entities, I'm not sure what the default behavior should be. 57d08d4 seemed to have changed something in that direction.

**Comment by viveleroi** [comment]
We have several tests for existing records but none specifically checking `findOne`.

https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/tests/validation.spec.js#L63-L151

A model's `validate` method should call our validators but I suppose there could be some scenario internal to mongoose that doesn't, we've seen it before.

Can you provide a more specific test case or steps to reproduce.

**Comment by freezy** [comment]
Ah sorry, I was browsing an old tree when looking at the tests, there's indeed much more now!

I'll try to provide a failing test, thanks!

**Comment by freezy** [comment]
Okay, here's a failing test:

```javascript
it('throws error when validating self with new duplicate value after retrieving with findOne()', function(done) {
    var User = mongoose.model('User', helpers.createUserSchema().plugin(uniqueValidator));

    var promise = new User(helpers.USERS[0]).save();
    promise.then(function() {
        var user = new User(helpers.USERS[1]);
        user.save().catch(done).then(function() {

            User.findOne({ username: helpers.USERS[1].username }).exec().catch(done).then(function(retrievedUser) {
                retrievedUser.email = helpers.USERS[0].email;
                retrievedUser.validate(function(err) {
                    err.should.be.an('object');
                    done();
                });
            });
        });
    });
    promise.catch(done);
});
```

**Comment by freezy** [comment]
Actually, not `findOne()` but `validate()` seems to be the problem. This fails too:

```javascript
it('throws error when validating self with new duplicate value', function(done) {
    var User = mongoose.model('User', helpers.createUserSchema().plugin(uniqueValidator));

    var promise = new User(helpers.USERS[0]).save();
    promise.then(function() {
        var user = new User(helpers.USERS[1]);
        user.validate(function(err) {
            expect(err).to.be.an('object');
            done();
        });
    });
    promise.catch(done);
});
```

In your test `throws error when saving self with new duplicate value`, you only check that `err` is not null, but you don't check that it actually originates from the validator. Validations could pass and `save()` will fail because of MongoDB honoring the unique constraint and you wouldn't know about it..

**Comment by freezy** [comment]
Any update? Can you confirm this?

**Comment by viveleroi** [comment]
Sorry for the delay, other things stole my attention but I've fixed this. I've also moved the issue with not fully validating errors to a new issue, #39

**Comment by freezy** [comment]
Thanks a lot! Will test once it's on NPM :)
