### ISSUE TITLE
Validation does not work when modifying existing document

### ISSUE THREAD

**Issue by rshov** [blakehaswell/mongoose-unique-validator#41]
When I change the name field of an existing document to be the same as another document, then I get the MongoDB error: E11000 duplicate key error index

The unique validator works for me when I create a new document, but not when modifying an existing document. Should it work for existing documents? I'm assuming it should.

My code is doing:
```javascript
Project.findById(projectId, function (err, project) {
    project.name = req.body.name;
    project.save( function (err) {
        // Here I get a MongoDB error instead of a Mongoose error!
    });
});
```

Thanks for any help

**Comment by viveleroi** [comment]
Can you please include your schema? Right now the `_id` field is used to identify whether a record exists or not, but only when mongoose tells us it's not a new entry.

**Comment by rshov** [comment]
Sure, I'm just using the default _id field, so I don't think that would be a problem.

I'm also using the mongoose-deep-populate plugin, just in case that can have a conflict, but I wouldn't expect it to.

```javascript
var mongoose = require('mongoose');
var deepPopulate = require('mongoose-deep-populate')(mongoose);
var uniqueValidator = require('mongoose-unique-validator');
var Schema = mongoose.Schema;

var ProjectSchema = new Schema({
    name        : {type:String, trim:true, unique:'Project name must be unique'},
    type        : {type:String, enum:enums.projectTypes},
    createdDate : {type:Date, default:Date.now},
    createdBy   : {type:Schema.ObjectId, ref:'User'},
    proposals   : [ {type:Schema.ObjectId, ref:'Proposal'} ],
    contacts    : [ {type:Schema.ObjectId, ref:'Contact'} ],
    documents   : [ {type:Schema.ObjectId, ref:'Document'} ]
});

/**
 * Indexes
 */
ProjectSchema.index({ 'name' : 1 });
ProjectSchema.index({ 'proposals' : 1 });

/**
 * Validations
 */
ProjectSchema.path('name').required(true, 'Project name cannot be blank');
ProjectSchema.path('type').required(true, 'Project type cannot be blank');

ProjectSchema.plugin(deepPopulate);
ProjectSchema.plugin(uniqueValidator, { message: 'The {PATH} must be unique.' });

module.exports = mongoose.model('Project', ProjectSchema);
```

Let me know if I can provide anything else. Thanks!

**Comment by viveleroi** [comment]
I can't reproduce this. I've modified one of our existing tests to use the same findById/save method you are and I've matched the `name` field in the schema. I did not use the "deep populate" plugin so you may want to try this without that.

When I edit a project so that it has a name already used by another record, the error is as I'd expect:

```
{ [ValidationError: Project validation failed]
  message: 'Project validation failed',
  name: 'ValidationError',
  errors:
   { name:
      { [ValidatorError: Error, expected `name` to be unique. Value: `a`]
        properties: [Object],
        message: 'Error, expected `name` to be unique. Value: `a`',
        name: 'ValidatorError',
        kind: 'user defined',
        path: 'name',
        value: 'a' } } }

**Comment by rshov** [comment]
Hmm, ok let me look into this further on my end. Maybe the deep-populate plugin is affecting it. I'll test it without that plugin. Glad to hear that it supports this scenario though. Thank you ver much for looking into this, and I'll get back with my results. Thanks
