### ISSUE TITLE
findOneAndUpdate({runValidators: true, context: 'query'}) not working properly

### ISSUE THREAD

**Issue by rafapaulin** [blakehaswell/mongoose-unique-validator#42]
When I run the findOneAndUpdate(), with the runValidators property, it propers validates everything.

the point is: i am sending a object to update the data, and if I do change one of the values that should be unique (aka. not updating them), and just update the others, it returns a error saying that those values should be unique.

is there any workaround this issue?

thanks

my update code:
```javascript
		Skill.findOneAndUpdate({'slug': req.params.slug}, req.body, {runValidators: true, context: 'query'}, function(err, doc){
			if(err) {
				res.status(500).json(err.errors);
				logger().user(err);
			} else {
				res.status(201).json({message: req.body.name + ' updated!'});
				logger().info(req.body.name + ' updated!', req.body);
			}
		});
```

my schema:
```javascript
	skillSchema = new Schema(
		{ 
			'name': {'type':String, 'required': true, 'minlength': 3, 'unique': true,  'uniqueCaseInsensitive': true},
			'slug': {'type': String, 'required': true, 'minlength': 3, 'unique': true, 'uniqueCaseInsensitive': true},
			'createdBy': String,
			'ability': {'type':String, 'required': true, 'minlength': 3},
			'prof': {'type':Boolean, 'required': true, 'default': false},
			'shortDesc': {'type':String, 'required': true, 'minlength': 3, 'maxlength': 145},
			'desc': {'type':String, 'required': true, 'minlength': 3},
		},
		{
			'collection': 'skills'
		}
	);
```

**Comment by viveleroi** [comment]
Based on what you've described, it's working in the plugin, as we test this specific scenario:

https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/tests/validation.spec.js#L95

If you can reduce this to a reproducible test (without any plugins, no reliance on code not present in your demo, etc) then I can look into it again.

**Comment by rafapaulin** [comment]
This snippets does not rely on any plugins other than mongoose itself and mongoose unique validator.

Actually, I am using a plugin to deal with error log on the console, but that is irrelevant in this case.

The unique validator, in a PUT (update) request with validators turned on, shouldnt' be ignoring fields that have not been changed?

**Comment by viveleroi** [comment]
My point is, your demo is incomplete because you haven't provided details on which errors are being triggered and you've included variables which aren't defined, so I can't see the data being passed in and can't verify which fields are changing.

The link provided tests for the use-case you're after, so from my end, I believe this is working as it expected in the plugin. If you can build a test which shows otherwise I'll look into it.

**Comment by rafapaulin** [comment]
You're right, my bad, I am sorry.

Lets to it again.

I am front ending with angular. When I access a endpoint of the item, it returns me the item properties, and a button for update it. when i hit the update, it pops a form pre filled with the info that is already there, where I can edit any properties of the object. When I send the form, the request is sent with an object with all the properties filled on the form to the server ("as if" it was a new POST).

Right, if I edit the {PATH} name of the object, and the new one is unique, everything work just fine.

But if I change just, lets say, the {PATH} desc, and let the name be the same as the original, on submit it returns a error message that {PATH} name should be unique (again, "as if" it was a new POST req).

I may be wrong, but considering that it is a update req, shouldn't the validator just ignore fields that does not chance, and validate only those that changed?

Thank you once more for your support.

PS.: do you need any front end code to evaluate this issue?

complete schema:
```javascript
'use strict';
var	mongoose = require('mongoose'),
	 uniqueV = require('mongoose-unique-validator'),
	  Schema = mongoose.Schema,
	
	skillSchema = new Schema(
		{ 
			'name': {'type':String, 'required': true, 'minlength': 3, 'unique': true},
			'slug': {'type': String, 'required': true, 'minlength': 3, 'unique': true},
			'createdBy': String,
			'ability': {'type':String, 'required': true, 'minlength': 3},
			'prof': {'type':Boolean, 'required': true, 'default': false},
			'shortDesc': {'type':String, 'required': true, 'minlength': 3, 'maxlength': 145},
			'desc': {'type':String, 'required': true, 'minlength': 3},
		},
		{
			'collection': 'skills'
		}
	);
	
skillSchema.plugin(uniqueV); // validate unique values

module.exports = mongoose.model('Skill', skillSchema); // Export for further use
```

complete update function:

```javascript
// == Requirements ================================================================= //
	var mongoose = require('mongoose'),
		 express = require('express'),
		  colors = require('colors'),
		  logger = require("../services/logger"),
		  router = express.Router(),
			slug = require('slug');
// ================================================================= Requirements == //

// == Global Variables ============================================================= //
	var modelNamer = function(collection){ 
		return require('../schemas/' + collection.slice(0, -1) + 'Schema') 
	};
// == Global Variables ============================================================= //

// == Update Item ================================================================== //
	.put('/:collection/:slug', function(req, res){
		req.body.slug = slug(req.body.name, { // Automatic generate slugs based on name
			replacement: '-',				  // replace spaces with replacement 
			symbols: true,					  // replace unicode symbols or not 
			remove: null,					  // (optional) regex to remove characters 
			lower: true,					  // result in lower case 
			charmap: slug.charmap,			  // replace special characters 
			multicharmap: slug.multicharmap	  // replace multi-characters 
		});

		modelNamer(req.params.collection)
			.findOneAndUpdate({'slug': req.params.slug}, req.body, {runValidators: true, context: 'query'}, function(err, doc){
				if(err) {
					res.status(409).json(err.errors);
					logger().debug(err.errors);
				} else {
					res.status(201).json({message: req.body.name + ' updated!'});
					logger().info(req.body.name + ' updated!', req.body);
				}
			});
	})
// ================================================================== Update Item == //
```

**Comment by rafapaulin** [comment]
So, any thoughts on this issue?

**Comment by viveleroi** [comment]
Please don't post whole portions of your app, that doesn't help me reduce this to a verifiable test. 

Anyway, I've determined the source of the problem and have pushed a fix. It's primarily due to `_id` not being available when using `find*Update` methods.

**Comment by rafapaulin** [comment]
Thanks! everything is working now. =D

I am sorry for bothering you

**Comment by yash-sharma9091** [comment]
Hi, with findOneAndUpdate it is showing the same message that throws from mongoDB `E11000 duplicate key error collection: cherrydoor.users index: email_1 dup key: { : "yash_sharma@seologistics.com" }` however when using with save it showing proper message `Error, expected `email` to be unique. Value: 'yashsharma@seologistics.com'`, please help me with that how to use proper message with findOneAndUpdate also,

```javascript
email: {
		type: String,
		lowercase: true,
    	trim: true,
		unique: true,
		uniqueCaseInsensitive: true,
		required: 'E-mail is required',
		validate: {
			validator: function(email) {
				return /^([\w-\.+]+@([\w-]+\.)+[\w-]{2,4})?$/.test(email);
			},
			message: '{VALUE} is not a valid email address'
		}
	}
UserSchema.plugin(uniqueValidator, { message: 'Error, expected {PATH} to be unique.' });
```

**Comment by viveleroi** [comment]
Sounds like you've missed the required mongoose configurations described here: https://github.com/blakehaswell/mongoose-unique-validator#find--updates

**Comment by yash-sharma9091** [comment]
Hi @viveleroi , i've follow all the required configs during call to `findOneAndUpdate` 
```javascript
User.findOneAndUpdate({'_id': req.params.id, 'password': decodedPassword }, 
        { "email": newEmail }, 
        { new: false, runValidators: true, context: 'query', setDefaultsOnInsert: true, fields: {email: 1, _id: 0 } },
        function(err, user) {
       // function body
});
```
i've mentioned `{ runValidators: true, context: 'query' }`, but still no success

**Comment by viveleroi** [comment]
I tried updating [our unit test](https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/tests/validation.spec.js#L155) to match your schema and method call but I'm still unable to reproduce the issue.

**Comment by PrashanthHegdeSgr** [comment]
@rafapaulin  Can you please tell me how did you solve it?
