### ISSUE TITLE
Using post('save')

### ISSUE THREAD

**Issue by tadjik1** [blakehaswell/mongoose-unique-validator#49]
Is it better solution using post hook for doing this validation?

since 4.5 version mongoose could handle mongo errors inside middleware:
http://mongoosejs.com/docs/middleware.html
find by Error Handling Middleware

```javascript
var schema = new Schema({
  name: {
    type: String,
    // Will trigger a MongoError with code 11000 when
    // you save a duplicate
    unique: true
  }
});

// Handler **must** take 3 parameters: the error that occurred, the document
// in question, and the `next()` function
schema.post('save', function(error, doc, next) {
  if (error.name === 'MongoError' && error.code === 11000) {
    next(new Error('There was a duplicate key error'));
  } else {
    next(error);
  }
});

// Will trigger the `post('save')` error handler
Person.create([{ name: 'Axl Rose' }, { name: 'Axl Rose' }]);
```

**Comment by viveleroi** [comment]
Glad they've added this - I'll have to check it out. I'd much rather use this especially since it could avoid another query - but I'm concerned how subdocument validation would work with this in place. Not that ours is stellar but I'm hesitant to break any backwards-compat. Luckily that's what semver is for.

**Comment by tadjik1** [comment]
@viveleroi could you give an example for this case? (subdocuments unique validation I mean)

**Comment by viveleroi** [comment]
Validation errors for nested documents/schemas. For example a [nested schema](https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/helpers.js#L176) throws a validation error like `Error, expected 'email' to be unique. Value: 'john.smith@gmail.com'`.

I quickly looked into using this method and my biggest concern is that it doesn't run in the validation context. 

- We can capture and reformat a `MongoError`, but we won't have access to a true `ValidationError` object. 
- We can mimic one but it still won't be able to match correctly.
- This won't cover calls to `.validate()`.

The goal of this plugin was to *validate* uniqueness before Mongo has a chance to reject the save, which we're losing if we simply capture errors post-save. 

I'll close the issue as invalid, but if you have more info, let me know.
