### ISSUE TITLE
More explicit errors for compound unique keys

### ISSUE THREAD

**Issue by danwkennedy** [blakehaswell/mongoose-unique-validator#50]
Kudos on the compound unique indexes. I'd like to request a slight change to the error that gets thrown for compound unique indexes. It'd be great to throw one error when the single compound index violates uniqueness. The error would have a list of paths/values describing the conditions. Right now, I get a list of errors as if they were individually breaking uniqueness.

**Comment by guzgarcia** [comment]
Still as unresolved, I have the same problem with the latest release.

**Comment by viveleroi** [comment]
It may not be possible to correct given we don't decide how paths are validated or errors are returned.

**Comment by rodrigogs** [comment]
+1

**Comment by viveleroi** [comment]
We don't specifically generate error messages, we provide a layer that runs validation and pass/fails it, Mongoose handles the actual error generation. I don't see any way we can address this issue without subverting their error logic, but I'm open to suggestions.
