### ISSUE TITLE
Release new version compatible with mongoose 4.9.1

### ISSUE THREAD

**Issue by sjorssnoeren** [blakehaswell/mongoose-unique-validator#58]
I've created and successfully merged a pull request last week with explicit async validation. I would like to use that in a few production products of mine, but I'd rather prefer to use the npm version than using a specific git url, due to some difficulties with CI. Is there any estimate the new version (currently) in master will be released and published to npm? Thanks

**Comment by viveleroi** [comment]
Closing as a duplicate of #57
