### ISSUE TITLE
Support sparse indexes

### ISSUE THREAD

**Issue by keith24** [blakehaswell/mongoose-unique-validator#61]
I ran into an issue like [this stackoverflow question](https://stackoverflow.com/questions/24430220/e11000-duplicate-key-error-index-in-mongodb-mongoose) where I had multiple documents with null values.  

According to the top answer in that question, an implementation using a sparse index instead of a unique index would solve this.

**Comment by viveleroi** [comment]
Can you provide example code, what happens currently, and what you would expect to happen? We've added some tests to cover use of sparse but must not be covering your use case.

**Comment by keith24** [comment]
It turned out to be an issue with my database.  Running

```
db.myCollection.dropIndexes()
```
fixed it.
