### ISSUE TITLE
Error: Duplicate key ( prefix emails )

### ISSUE THREAD

**Issue by RayRed1** [blakehaswell/mongoose-unique-validator#62]
When i use prefix emails like 'nightmare+1@gmail.com' it handling mongo error with code 11000, but it has incorrect message.
`E11000 duplicate key error collection: <collection-name>.days index: date_1 dup key: { : null }`

**Comment by viveleroi** [comment]
That error has nothing to do with an email field, nor is that an error from this plugin. Mongo is complaining about an unrelated field.
