### ISSUE TITLE
The mongoose-unique-validator plugin is not catching the E11000 duplicate key errors

### ISSUE THREAD

**Issue by Teebo** [blakehaswell/mongoose-unique-validator#63]
I have installed the mongoose-unique-validator, it appears on the dependencies section of my package.json. 

versions:
    "mongoose": "^4.7.2",
    "mongoose-unique-validator": "^1.0.5",

I have required it in my model file where I define my schema for a collection like
`const uniqueValidator = require('mongoose-unique-validator');`

defined my schema here...

and applied it as a plugin like 
`mySchema.plugin(uniqueValidator, {message: "There is already a user with {PATH}"});`

In spite of this, I am still getting the E11000 duplicate key errors from mongo db

`MongoError: insertDocument :: caused by :: 11000 E11000 duplicate key error index: .....`

I am not sure if I am missing something here, I would appreciate any assistance.

**Comment by viveleroi** [comment]
Can you push a test repo that demonstrates/reproduces the issue? The snippets you've provided seem fine but there has to be something else.

**Comment by Teebo** [comment]
Okay I will create a repo that demonstrates/reproduces the issue, In the mean time I can send you my schema and the code where I call the .save method for the collection as I am at work now,
`const mongoose = require('mongoose');
var Schema = mongoose.Schema;

var MySchema = new Schema({
    user_id: {type : String,require : true},
    name: {type : String,require : true},
    surname: {type : String,require : true},
    username: {type : String,require : true, unique:  true}
},{timestamps : true});

//Here I am attaching methods to my schema e.g ,
MySchema .methods.generateJwt = () => {
.....
}
//more schema methods
MySchema.plugin(uniqueValidator, {message: "There is already a user with {PATH}"});
var MyModel2 = mongoose.model('MyModel2 ',MySchema );
module.exports = MyModel2 ;`

And the code to save the document is as follows..
`      let newMyModel1 = new MyModel1({
            });

	  newMyModel1 .save(function(err,doc){
            if(err){console.log("There was an error saving the moving agent");throw err;}
	   console.log("Successfully created doc"); 
            var newMyModel2= new MyModel2 ({
                    user_id: req.data._id,
                    name: req.data.name,
                    surname: req.data.surname,
                    username: req.data.username 
            });

            newMyModel2 .save(function(err){
                if(err){console.log("There was an error saving model 2");throw err;}
                console.log("Successfully created doc2");
            });
            });`

Could it be that I am saving the my model document inside another insertion callback? As you can see I am saving one model document (MyModel1) then if it is successfully saved, I am saving the one that I have the mongoose-unique-validator on (MyModel2), which is the one I have provided a schema for. I hope this is enough for now, thanks

**Comment by Teebo** [comment]
I will close this one for some reason the reproduction is not successful, I will debug
