### ISSUE TITLE
Why does the docs doesn't specify the --save flag when installing?

### ISSUE THREAD

**Issue by jjjjcccjjf** [blakehaswell/mongoose-unique-validator#72]
Hello, I'm quite new to Node.js and I know this is a noob question. The title says it all. Why does the docs doesn't specify the --save flag when installing? Isn't it a considered to be a dependency already? Thanks

**Comment by viveleroi** [comment]
No real reason, it was just written that way.

**Comment by jjjjcccjjf** [comment]
Then if I upload it to my server and install my dependencies, wouldn't it go missing because it doesn't have the --save flag?

**Comment by viveleroi** [comment]
It's not up to a dependency to dictate how someone uses NPM. Once you learn the basics of NPM you should able to determine for yourself whether you want `--save` or `--save-dev`, etc. In this case, it's likely that `--save` is used most so I agree we can include it in the example, but omitting it shouldn't mean you can't use it.

**Comment by jjjjcccjjf** [comment]
Thank you for your explanation
