### ISSUE TITLE
Updating Errors when String Field with unique and uniqueCaseInsensitive

### ISSUE THREAD

**Issue by lecosas** [blakehaswell/mongoose-unique-validator#76]
I think there is a bug when you try to update a document with a string field unique and uniqueCaseInsensitive. Example:

```
const ProductSchema = mongoose.Schema({
    name: {
        type: String,
        trim: true,
        unique : true,
        uniqueCaseInsensitive: true,
        required: [true , 'Campo nome é obrigatório.'], 
    }, 
    price: {
        type: number
    }
});
```
Document: 
{
   _id: xyz,
   name: Pen,
   price: 1
}

{
   _id: abc,
   name: Pencil,
   price: 1
}

If you update the 'xyz' product to name 'Pencil', the validator accept. 
I'm using Update method from Moongose.

**Comment by viveleroi** [comment]
Can you please reproduce the issue via a repo or test case? I need to be able to see the full process you're taking. We test for this with `findOneAndUpdate` and it's working: https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/tests/validation.spec.js#L162
