### ISSUE TITLE
Fails with "SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode" on Node.js 4

### ISSUE THREAD

**Issue by markstos** [blakehaswell/mongoose-unique-validator#78]
Node.js 4 is still an LTS release, but a recent update removed a "use strict" line which broke the code on Node.js 4.

**Comment by viveleroi** [comment]
Fixed by ab228a93416e44b4da0d1877461b08813fc24294

**Comment by markstos** [comment]
Thanks @viveleroi. I look forward to having this fix released. It is important to those using Node.js 4 who are upgrading to Mongoose 5 and would like the compatibility fixes for Mongoose 5 in the newer version of this module.

**Comment by viveleroi** [comment]
Released as 2.0.1.
