### ISSUE TITLE
unique works while update ip not exists

### ISSUE THREAD

**Issue by vaggeliskls** [blakehaswell/mongoose-unique-validator#92]
First of all thank you for your excellent work.
I will try to describe my issue:

My schema
```
let UserSchema = new Schema({
  name: { type: String },
  email: {
    type: String,
    unique: true,
    trim: true,
    lowercase: true
  }
});
```

DB dummy Data (_id name email)
```
11111111  dummy1  dummy1@ex.com
22222222  dummy2  dummy2@ex.com
33333333  dummy3  dummy3@ex.com
```
My query
```
await User.findOneAndUpdate( { _id: req.params.userId} ,{
          name: req.body.name,
          email: req.body.email,
        }, {
          new: true,
          runValidators: true,
          context: 'query'
        }
      )
      .orFail( () => new NotFoundError() )
      .exec();
```
My API
```
http:localhost/api/user/:userId
```

Problem - Example:

- When userId=11111111 (exists) the library works perfectly (indication of unique, correctly update when email value is the same)
- When userId=00000000 (not exists) and email=dummy7@ex.com (not exists) there isn't any unique value nor a userId exists . As a result a NotFoundError throws on .orFail()
- **When userId=00000000 (not exists) and email=dummy1@ex.com (exists) the library not working as expected. The libraries correctly indicates that the email is not unique while _id not exists in DB.**

Any suggestions ?
Thank you.

**Comment by viveleroi** [comment]
You need a compound index for email *and* userid to be checked together. id is unique, email is unique, but those are separate so the plugin will query them separately. 

See here for an example:

https://github.com/blakehaswell/mongoose-unique-validator/blob/master/test/helpers.js#L109
