### ISSUE TITLE
Support a "transform function" before value is checked

### ISSUE THREAD

**Issue by timster** [blakehaswell/mongoose-unique-validator#96]
I have a case where a value is being encrypted using a pre-save hook before being inserted into Mongo. But that value still needs to be unique. Think email addresses.

So to check for a unique email address, we need to encrypt the email address, then check for a duplicate of the encrypted value.

It would be great if I could do this through this plugin. I modified my local copy to do this, and it seems to work. It allows for passing any kind of "transform function" that will be run on the value prior to check if it's unique. I put this right after the `options.uniqueCaseInsensitive` case.

```javascript
const transformFunction = get(path, 'options.transformFunction');
if (transformFunction) {
   pathValue = transformFunction(pathValue);
}
```

Then in my schema definition, I can do this:

```javascript
import { encrypt } from 'super-secure-functions'

const UserSchema = new mongoose.Schema({
  email: { type: String, required: true, unique: true, transformFunction: encrypt },
})
```

Would you entertain a pull request for such a feature? Or is there another way to do this that I'm not aware of?

**Comment by viveleroi** [comment]
I don't think we'll add this to the plugin, we should only be validating the final data set that gets added to the database. If data is being transformed after validation that feels like a major flaw in the logical order.
